"""Derive Rudi's TUXEDO outfit sprite prompts from his default (hoodie) set.

Mechanical, deterministic, burns ZERO image generations: reads
characters/rudi/sprite_prompts.txt, swaps ONLY the identical outfit clause
(pink hoodie + navy shorts -> black tuxedo) in every block, repoints each
relpath sprites/<p> -> outfits/tuxedo/<p>, reorders so the highest-traffic
party poses generate first (a partial set still looks great), renumbers
[01..], and writes characters/rudi/outfits/tuxedo/prompts.txt.

Keeping every other word of the master description identical is what holds the
character consistent across the two outfits -- only the clothing clause and the
'Pose:' line differ. The script ASSERTS the hoodie clause is present in every
block and fails loudly otherwise, so a hoodie prompt can never silently ship
into the tuxedo set.

Run (no venv needed, stdlib only):
  python scripts/_gen_rudi_tuxedo_prompts.py
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "characters" / "rudi" / "sprite_prompts.txt"
OUT_DIR = ROOT / "characters" / "rudi" / "outfits" / "tuxedo"
OUT = OUT_DIR / "prompts.txt"

# The exact clothing clause in every default block (verified: 39/39 identical).
HOODIE = ("He wears an oversized cozy soft-pink pullover hoodie (hood down, "
          "front kangaroo pocket and drawstrings) and dark navy denim shorts, "
          "with small orange clawed paws.")
# Same chibi red panda, new clothes. Keep it a "little"/mascot tux so the
# oversized-head chibi proportions (described elsewhere in the block) survive.
TUX = ("He wears a sharp little black tuxedo: a fitted black tux jacket with "
       "satin peaked lapels over a crisp white dress shirt, a black bowtie at "
       "the collar, and black dress trousers, with small orange clawed paws.")

# Highest-traffic poses first: idle/talk/listen/greet/party/toast dominate a
# party's screen time, so if ChatGPT caps stop the grind partway, the tuxedo
# set already covers what guests actually see. Paths are the ORIGINAL
# sprites/<p> keys; anything not listed keeps its original file order after.
PRIORITY = [
    "sprites/neutral/idle.png",
    "sprites/speech/talking.png",
    "sprites/speech/explaining.png",
    "sprites/speech/listening.png",
    "sprites/greeting/casual_wave.png",
    "sprites/party/celebrate.png",
    "sprites/party/birthday.png",
    "sprites/toast/raising_glass.png",
    "sprites/positive/smirk.png",
    "sprites/positive/hyped.png",
    "sprites/positive/confident.png",
    "sprites/movement/vibing.png",
    "sprites/greeting/peace_out.png",
    "sprites/thinking/pondering.png",
    "sprites/movement/arriving.png",
]

HEADER = (
    "RUDI - TUXEDO OUTFIT SPRITE PROMPTS (for GPT-4o / DALL-E image gen)\n"
    "======================================================================\n"
    "AUTO-GENERATED by scripts/_gen_rudi_tuxedo_prompts.py from the default\n"
    "hoodie set -- do not hand-edit; edit the generator or the source file.\n"
    "Only the clothing clause (-> black tuxedo) and relpath (-> outfits/\n"
    "tuxedo/) differ from characters/rudi/sprite_prompts.txt. Blocks are\n"
    "ordered highest-traffic-first so a partial grind still covers the party.\n"
    "======================================================================\n\n"
)

README = (
    'Alt outfit "tuxedo" - black-tie formal set for Rudi (birthday-party VIP\n'
    "look), an upgrade from his default pink-hoodie casual outfit. Sprites are\n"
    "generated by the wardrobe pipeline into this tree, mirroring the default\n"
    "characters/rudi/sprites/ layout. Prompts: prompts.txt (auto-generated).\n"
    "The live default sprites/ tree still holds the casual hoodie outfit.\n"
)


def parse_blocks(text: str):
    """Yield (relpath, body) for each '[NN] <relpath>\\n----\\n<body>' block."""
    lines = text.splitlines()
    i, blocks = 0, []
    while i < len(lines):
        line = lines[i].strip()
        if line.startswith("[") and "]" in line:
            relpath = line.split("]", 1)[1].strip()
            # skip the dashed underline row
            body_lines, j = [], i + 2
            while j < len(lines) and not (lines[j].strip().startswith("[")
                                          and "]" in lines[j]):
                body_lines.append(lines[j])
                j += 1
            body = "\n".join(body_lines).strip()
            if body:
                blocks.append((relpath, body))
            i = j
        else:
            i += 1
    return blocks


def main() -> None:
    blocks = parse_blocks(SRC.read_text(encoding="utf-8"))
    if len(blocks) != 39:
        raise SystemExit(f"expected 39 source blocks, parsed {len(blocks)}")

    converted = {}   # original relpath -> (tux_relpath, tux_body)
    for relpath, body in blocks:
        if HOODIE not in body:
            raise SystemExit(f"hoodie clause missing in block {relpath!r} -- "
                             "refusing to emit a possibly-wrong tuxedo prompt")
        if not relpath.startswith("sprites/"):
            raise SystemExit(f"unexpected relpath {relpath!r} (want sprites/...)")
        tux_body = body.replace(HOODIE, TUX)
        tux_rel = "outfits/tuxedo/" + relpath[len("sprites/"):]
        converted[relpath] = (tux_rel, tux_body)

    # Priority first (in listed order), then the rest in original file order.
    ordered, seen = [], set()
    for key in PRIORITY:
        if key in converted:
            ordered.append(key)
            seen.add(key)
        else:
            print(f"  note: priority path not in source, skipping: {key}")
    for relpath, _ in blocks:
        if relpath not in seen:
            ordered.append(relpath)
            seen.add(relpath)

    parts = [HEADER]
    for n, key in enumerate(ordered, 1):
        tux_rel, tux_body = converted[key]
        parts.append(f"[{n:02d}] {tux_rel}\n")
        parts.append("-" * 70 + "\n")
        parts.append(tux_body + "\n\n")

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    OUT.write_text("".join(parts), encoding="utf-8")
    (OUT_DIR / "README.txt").write_text(README, encoding="utf-8")

    # Safety: no old-outfit wording may survive into any prompt BODY. Scan the
    # converted bodies only -- the header intentionally names the "hoodie" set.
    for key in ordered:
        low = converted[key][1].lower()
        for banned in ("hoodie", "denim", "navy", "pink pullover", "pullover"):
            if banned in low:
                raise SystemExit(f"BANNED word {banned!r} leaked into {key}")

    print(f"wrote {len(ordered)} tuxedo blocks -> {OUT}")
    print(f"first 3 poses: {[converted[k][0] for k in ordered[:3]]}")


if __name__ == "__main__":
    main()
